/**
 * @File Name          : DxSample.cls
 * @Description        :
 * @Author             : dkowalec@mdvip.com
 * @Group              :
 * @Last Modified By   : dkowalec@mdvip.com
 * @Last Modified On   : 12/11/2019, 11:05:01 AM
 * @Modification Log   :
 * Ver       Date            Author      		    Modification
 * 1.0    12/11/2019   dkowalec@mdvip.com     Initial Version
 **/
public with sharing class DxSample {
  public DxSample() {
  }
}
