/**
 * @File Name          : DxSample2.cls
 * @Description        :
 * @Author             : dkowalec@mdvip.com
 * @Group              :
 * @Last Modified By   : dkowalec@mdvip.com
 * @Last Modified On   : 12/11/2019, 11:11:57 AM
 * @Modification Log   :
 * Ver       Date            Author              Modification
 * 1.0    12/11/2019   dkowalec@mdvip.com     Initial Version
 **/
public with sharing class DxSample2 {
  public DxSample2() {
  }
}
